### ISSUE TITLE
rpmlint fails on UnicodeDecodeError:

### ISSUE THREAD

**Issue by pdancak** [rpm-software-management/rpmlint#1297] opened 2024-11-07 10:44 UTC
I have tried to run the rpmlint on the pihpsdr-debuginfo-2.0.8-rc120241105git7ad62180-1.fc42.x86_64.rpm. The rpmlint failed with this error:

`rpmlint --verbose pihpsdr-debuginfo-2.0.8-rc120241105git7ad62180-1.fc42.x86_64.rpm
3033 blocks
(none): E: fatal error while reading pihpsdr-debuginfo-2.0.8-rc120241105git7ad62180-1.fc42.x86_64.rpm: 'utf-8' codec can't decode byte 0xe0 in position 444: invalid continuation byte
Traceback (most recent call last):
  File "/usr/bin/rpmlint", line 8, in <module>
    sys.exit(lint())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/rpmlint/cli.py", line 176, in lint
    sys.exit(lint.run())
             ^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/rpmlint/lint.py", line 108, in run
    return self._run()
           ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/rpmlint/lint.py", line 76, in _run
    self.validate_files(self.options['rpmfile'])
  File "/usr/lib/python3.12/site-packages/rpmlint/lint.py", line 246, in validate_files
    self.validate_file(pkg, pkg == packages[-1])
  File "/usr/lib/python3.12/site-packages/rpmlint/lint.py", line 272, in validate_file
    raise e
  File "/usr/lib/python3.12/site-packages/rpmlint/lint.py", line 265, in validate_file
    self.run_checks(pkg, is_last)
  File "/usr/lib/python3.12/site-packages/rpmlint/lint.py", line 281, in run_checks
    fn(pkg)
  File "/usr/lib/python3.12/site-packages/rpmlint/checks/AbstractCheck.py", line 17, in check
    return self.check_binary(pkg)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/rpmlint/checks/BinariesCheck.py", line 698, in check_binary
    self.run_elf_checks(pkg, pkgfile)
  File "/usr/lib/python3.12/site-packages/rpmlint/checks/BinariesCheck.py", line 587, in run_elf_checks
    self.readelf_parser = ReadelfParser(pkgfile.path, pkgfile.name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/rpmlint/readelfparser.py", line 357, in __init__
    self.program_header_info = ElfProgramHeaderInfo(pkgfile_path, extra_flags)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/rpmlint/readelfparser.py", line 143, in __init__
    self.parse()
  File "/usr/lib/python3.12/site-packages/rpmlint/readelfparser.py", line 146, in parse
    r = subprocess.run(['readelf', '-W', '-l', self.path] + self.extra_flags, encoding='utf8',
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 1209, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 2153, in _communicate
    stdout = self._translate_newlines(stdout,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 1086, in _translate_newlines
    data = data.decode(encoding, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 444: invalid continuation byte`

The rpm package, which reproduces it is attached.
[rpm_file.tar.gz](https://github.com/user-attachments/files/17660207/rpm_file.tar.gz)

**Comment by danigm** [comment] 2024-11-08 08:44
Looks like this is a duplicate of https://github.com/rpm-software-management/rpmlint/issues/1147, fixed here: https://github.com/rpm-software-management/rpmlint/commit/af2c43fa814723a4d8f78cdfba8f94862368716f

Maybe this is a patch to backport in Fedora package, or update the rpmlint package to version 2.6.1

**Closed by danigm** 2024-11-08 08:44 UTC
